# -*- coding: utf-8 -*-
"""anastasya_skripsi_finalfix!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yanbFY6o8s95M-mfhrRsAATiKNhGFq3y

Scrapping
"""

import pandas as pd
import numpy as np
import re
import string
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from google.colab import drive
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
from scipy.sparse import csr_matrix, hstack
import random
import csv
import ast  # buat konversi string ke list jika perlu
!pip install seaborn
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/drive/MyDrive/data/scrapping_baru.csv')

if 'content' not in data.columns:
    raise KeyError("The dataset does not contain a 'content' column.")

import pandas as pd

# Baca dataset kamu (ganti nama file sesuai file kamu)
df = pd.read_csv('/content/drive/MyDrive/data/scrapping_baru.csv')

# Pastikan kolom rating ada dan bernama 'rating'
# Kalau namanya beda, ganti sesuai kolom kamu
print(df.columns)  # cek dulu nama kolom

# Kelompokkan rating jadi dua kategori
def label_sentiment(score):
    if score in [1, 2]:
        return 'Negatif'
    elif score in [3, 4, 5]:
        return 'Positif'

df['kategori'] = df['score'].apply(label_sentiment)

# Hitung jumlah masing-masing kategori
sentiment_count = df['kategori'].value_counts()
sentiment_percent = df['kategori'].value_counts(normalize=True) * 100

# Tampilkan hasil
print("Jumlah masing-masing kategori:")
print(sentiment_count)
print("\nPersentase masing-masing kategori (%):")
print(sentiment_percent)

# (Opsional) buat tabel ringkas
result = pd.DataFrame({
    'Jumlah': sentiment_count,
    'Persentase (%)': sentiment_percent.round(2)
})

print("\nTabel hasil pengelompokan:")
print(result)

"""# Preprocessing

"""

data.info()

"""Case folding"""

def case_folding(content):
    return str(content).lower()

data['case_folding'] = data['content'].apply(case_folding)
print("Case Folding Completed")

display(data[['content', 'case_folding']].head(10))

"""Data Cleaning"""

def cleaning(content):
    content = str(content)
    content = re.sub(r'http\S+|www\S+', '', content)               # hapus link
    content = re.sub(r'\@\w+', '', content)                        # hapus mention
    content = re.sub(r'\d+', '', content)                          # hapus angka
    content = content.translate(str.maketrans('', '', string.punctuation))  # hapus tanda baca
    content = re.sub(r'\s+', ' ', content)                         # hapus spasi berlebihan
    content = re.sub(r'[^\w\s]', '', content, flags=re.UNICODE)               # hapus emoji dan karakter non-ASCII
    return content

data['cleaning'] = data['case_folding'].apply(cleaning)
print("Cleaning Completed")

display(data[['case_folding', 'cleaning']].head(10))

# Pastikan tidak ada NaN atau nilai kosong dalam pipeline sebelum masuk tokenizer
data = data.dropna(subset=['cleaning'])  # hapus NaN
data = data[~data['cleaning'].astype(str).str.strip().eq("")]  # hapus string kosong

data.info()

"""Tokenisasi"""

def tokenize(content):
    return str(content).split()

data['tokenisasi'] = data['cleaning'].apply(tokenize)
print("Tokenization Completed")

display(data[['cleaning', 'tokenisasi']].head(10))

"""Normalisasi"""

# pake encoding biar file bisa dibaca dengan benar
normalization_dict = pd.read_csv('/content/drive/MyDrive/data/kamus_normalisasi_barulagi.csv', sep=';', encoding='ISO-8859-1')
normalization_dict = dict(zip(normalization_dict['before'], normalization_dict['after']))

def normalized_words(content):
    return [normalization_dict.get(word, word) for word in content]

data['normalisasi'] = data['tokenisasi'].apply(normalized_words)
data[['tokenisasi','normalisasi']].head(10)

"""Stopword"""

stop_words = set(stopwords.words('indonesian'))
def remove_stopwords(content):
    return [word for word in content if word not in stop_words]

data['stopword_removal'] = data['normalisasi'].apply(remove_stopwords)
print("Stopword Removal Completed")

display(data[['normalisasi', 'stopword_removal']].head(10))

"""Stemming"""

!pip install Sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(content):
    if isinstance(content, list):
        return [stemmer.stem(word) for word in content if isinstance(word, str) and word.isalpha()]
    return []

data['stemming'] = data['stopword_removal'].apply(stemming)
print("Stemming Completed")

display(data[['stopword_removal', 'stemming']].head(10))

# Buat kolom baru hasil preprocessing
data["hasil_preprocessing"] = data["stemming"]

# Simpan full data
data.to_csv('/content/drive/MyDrive/data/hasil/TixID_Full_Data.csv', index=False)

# Simpan kolom hasil stemming aja
data["hasil_preprocessing"].to_csv('/content/drive/MyDrive/data/hasil/Clean_Data.csv', index=False)

# nampilin
data

data.info()

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
import seaborn as sns

stopwords = set(STOPWORDS)
sns.set(style='whitegrid')
plt.style.use('fivethirtyeight')

def wordcloud(data, title=None):
    # Gabungkan list of tokens jadi string
    combined_text = ' '.join([' '.join(words) for words in data if isinstance(words, list)])

    wordcloud = WordCloud(
        background_color='white',
        stopwords=stopwords,
        max_words=100,
        max_font_size=40,
        scale=4,
        random_state=25
    ).generate(combined_text)

    fig = plt.figure(5, figsize=(9, 10))
    plt.axis('off')
    if title:
        fig.suptitle(title, fontsize=27)
        fig.subplots_adjust(top=2.3)
    plt.imshow(wordcloud)
    plt.show()

# Panggil fungsi
wordcloud(data['hasil_preprocessing'], title="WordCloud Hasil Preprocessing")

"""# Labeling

Labeling
"""

# --- BACA KAMUS POSITIF DAN NEGATIF ---
lexicons_positive = dict()
with open('/content/drive/MyDrive/data/positive - positive.csv', 'r') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    for row in reader:
        word = row[0].strip().lower()
        value = int(row[1])
        if len(word.split()) == 1:
            lexicons_positive[word] = value

lexicons_negative = dict()
with open('/content/drive/MyDrive/data/negative - negative.csv', 'r') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    for row in reader:
        word = row[0].strip().lower()
        value = int(row[1])
        if len(word.split()) == 1:
            lexicons_negative[word] = -abs(value)

print(f"Jumlah kata dalam lexicon positif: {len(lexicons_positive)}")
print(f"Jumlah kata dalam lexicon negatif: {len(lexicons_negative)}")


# ---FUNGSI PENILAIAN SENTIMEN ---
def determine_lexicon_score(text):
    if isinstance(text, list):
        positive_score = sum(lexicons_positive.get(word.lower().strip(), 0) for word in text)
        negative_score = sum(lexicons_negative.get(word.lower().strip(), 0) for word in text)
        lexicon_score = positive_score + negative_score
        polarity = 'positif' if lexicon_score >= 0 else 'negatif'
        return lexicon_score, polarity
    return 0, 'negatif'


# --- APLIKASIKAN KE DATA ---
results = data["hasil_preprocessing"].apply(determine_lexicon_score)
results = list(zip(*results))

data['polarity_score'] = results[0]
data['polarity'] = results[1]

print(data['polarity'].value_counts())


# ---SIMPAN DATA ---
data.to_csv('/content/drive/MyDrive/data/hasil/TixID_label.csv', index=False)
data[["hasil_preprocessing", "polarity_score", "polarity"]].to_csv('/content/drive/MyDrive/data/hasil/dataset_polarity.csv', index=False)

data[['hasil_preprocessing', 'polarity_score', 'polarity']].head(10)

# Hitung jumlah masing-masing kategori sentimen dari hasil lexicon
sentiment_counts = data['polarity'].value_counts()

# Plot
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
plt.bar(sentiment_counts.index, sentiment_counts.values, color=['green', 'red'])
plt.title('Distribusi Sentimen Berdasarkan Lexicon')
plt.xlabel('Polaritas Sentimen')
plt.ylabel('Jumlah')
plt.grid(axis='y', linestyle='--', alpha=0.7)
for i, v in enumerate(sentiment_counts.values):
    plt.text(i, v + 1, str(v), ha='center', fontweight='bold')
plt.show()

stopwords = set(STOPWORDS)
sns.set(style='whitegrid')
plt.style.use('fivethirtyeight')

def generate_wordcloud(data_series, title=None):
    # Gabungkan semua kata dari list ke string
    combined_text = ' '.join([' '.join(words) for words in data_series if isinstance(words, list)])

    wordcloud = WordCloud(
        background_color='white', stopwords=stopwords, max_words=100,
        max_font_size=40, scale=4, random_state=25
    ).generate(combined_text)

    # Plot
    plt.figure(figsize=(10, 8))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    if title:
        plt.title(title, fontsize=20)
    plt.show()

# WordCloud untuk sentimen positif
generate_wordcloud(data[data['polarity'] == 'positif']['hasil_preprocessing'], title='WordCloud Sentimen Positif')

stopwords = set(STOPWORDS)
sns.set(style='whitegrid')
plt.style.use('fivethirtyeight')

def generate_wordcloud(data_series, title=None):
    # Gabungkan semua kata dari list ke string
    combined_text = ' '.join([' '.join(words) for words in data_series if isinstance(words, list)])

    wordcloud = WordCloud(
        background_color='white', stopwords=stopwords, max_words=100,
        max_font_size=40, scale=4, random_state=25
    ).generate(combined_text)

    # Plot
    plt.figure(figsize=(10, 8))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    if title:
        plt.title(title, fontsize=20)
    plt.show()

# WordCloud untuk sentimen negatif
generate_wordcloud(data[data['polarity'] == 'negatif']['hasil_preprocessing'], title='WordCloud Sentimen Negatif')

"""# Processing

Splitting
"""

import ast
from sklearn.model_selection import train_test_split
import pandas as pd

# Load dan siapkan data - Load the full data instead of just the clean data
data_full = pd.read_csv('/content/drive/MyDrive/data/hasil/dataset_polarity.csv')

# Ubah list string jadi list Python - Apply ast.literal_eval to the correct column
data_full['hasil_preprocessing'] = data_full['hasil_preprocessing'].apply(ast.literal_eval)

# Gabungkan token jadi string kalimat
data_full['hasil_preprocessing_str'] = data_full['hasil_preprocessing'].apply(lambda x: ' '.join(x))

# Define X and y
X = data_full['hasil_preprocessing_str']
y = data_full['polarity']

# Split data sebelum TF-IDF
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Simpan hasil split ke file CSV (optional)
X_train.to_csv('/content/drive/MyDrive/data/hasil/X_train_text.csv', index=False)
X_test.to_csv('/content/drive/MyDrive/data/hasil/X_test_text.csv', index=False)
y_train.to_csv('/content/drive/MyDrive/data/hasil/y_train.csv', index=False)
y_test.to_csv('/content/drive/MyDrive/data/hasil/y_test.csv', index=False)

# Info jumlah data
print("Split 80:20")
print("Train:", len(X_train))
print("Test :", len(X_test))
print("Total:", len(X_train) + len(X_test))
print("Split selesai dan disimpan.")

"""TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Inisialisasi vectorizer
vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

# TF-IDF untuk train/test
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print(X_test_tfidf)

import pandas as pd
import numpy as np

# Ambil semua fitur (kata) dari TF-IDF
fitur = vectorizer.get_feature_names_out()

# Ubah sparse matrix ke bentuk array
tfidf_array = X_train_tfidf.toarray()

# Hitung rata-rata bobot setiap kata di seluruh dokumen
rata2_tfidf = np.mean(tfidf_array, axis=0)

# Buat dataframe kata + bobot rata-rata
df_tfidf = pd.DataFrame({
    'Kata': fitur,
    'Bobot_TFIDF': rata2_tfidf
})

# Ambil 10 kata dengan bobot tertinggi
top10 = df_tfidf.sort_values(by='Bobot_TFIDF', ascending=False).head(10)

print(top10)

"""Klasifikasi NB"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, ConfusionMatrixDisplay
)

# === Latih model ===
clf = MultinomialNB()
clf.fit(X_train_tfidf, y_train)

# === Prediksi data uji ===
predicted = clf.predict(X_test_tfidf)

hasil_klasifikasi = pd.DataFrame({
    'stem_review': X_test,              # isi review yang diuji (teks asli)
    'Actual_Label': y_test,             # label asli
    'Predicted_Label': predicted        # label hasil prediksi
})

# Tampilkan beberapa baris hasil klasifikasi
print("✅ Hasil Klasifikasi:")
display(hasil_klasifikasi.head(10))

# Simpan hasil klasifikasi ke CSV
hasil_klasifikasi.to_csv('hasil_klasifikasi_nb.csv', index=False)
print("✅ Hasil klasifikasi berhasil disimpan ke 'hasil_klasifikasi_nb.csv'.")

# Evaluasi
print("✅ Evaluasi Naive Bayes:")
print("Accuracy :", accuracy_score(y_test, predicted))
print("Precision:", precision_score(y_test, predicted, pos_label='positif', average='binary'))
print("Recall   :", recall_score(y_test, predicted, pos_label='positif', average='binary'))
print("F1 Score :", f1_score(y_test, predicted, pos_label='positif', average='binary'))

print("\n=== Classification Report ===")
print(classification_report(y_test, predicted))

"""Confusion Matrix"""

cm = confusion_matrix(y_test, predicted, labels=['positif', 'negatif'])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['positif', 'negatif'])
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()

print("\n=== Classification Report ===")
print(classification_report(y_test, predicted, zero_division=0))